// L system class. This generates a string that can be used as an instruction set to create something.
// This is based on kivyfreakt's L System, which can be found here: https://github.com/kivyfreakt/LSystem
// It has been adapted for use in Unreal Engine, alongside other changes such as a different system for probability.

#pragma once

#include "CoreMinimal.h"
#include "LGrammar.h"
#include "LRule.h"

/**
 * 
 */
class PROCEDURALLIGHTNING_API LSystem
{
public:
	// Constructor and destructor.
	LSystem();
	~LSystem();

	// Build the L system.
	void Build(FString axiom, TArray<FString> rules, int iterations);

	// Used to access the string generated by the L system.
	FString GetResult();

private:
	// The resultant string of the L system.
	FString Result;
};
